package com.cg.bms.theatreservice.model;

import java.util.List;
import java.util.Set;

import org.springframework.data.annotation.Id;
//import org.springframework.data.mongodb.core.mapping.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

//lockedByShowTimeId : empty if seatstatus is available

@DynamoDBTable(tableName = "Seat")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Seat {
	
	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	//@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
	private String _id;
	
	@DynamoDBAttribute
	private Integer row;
	
	@DynamoDBAttribute
	private Integer column;
	
	@DynamoDBAttribute
	private List<String> lockedByShowTimeIds;
	//private SeatStatus seatStatus;
	
	@DynamoDBAttribute
	private String screenId;
	

}
