package com.cg.bms.theatreservice.model;


import java.util.List;
import java.util.Set;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@DynamoDBTable(tableName = "Theatre")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class Theatre {
	
	
	//@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private String _id;
	
    @DynamoDBAttribute
	private String name;
    
    @DynamoDBAttribute
	private List<String> screenIds;
    
    @DynamoDBAttribute
	private String cityId;
	
}

