package com.cg.bms.bookingservice.model;

import java.util.Date;
import java.util.List;
import java.util.Set;

import org.springframework.data.annotation.Id;
//import org.springframework.data.mongodb.core.mapping.Document;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


//need @JsonPropert WRITE_ONLY instead of JsonIgnore, so that ids are deserialized, but not visible.
//Replace all @JsonIgnores with above


@DynamoDBTable(tableName = "Booking")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Getter
@Setter
public class Booking {
	
	
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	//@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
	private String _id;
    
    @DynamoDBAttribute
	private String theatreId;
    
    @DynamoDBAttribute
	private String screenId;
    
    @DynamoDBAttribute
	private String userId;
    
    @DynamoDBAttribute
	private String movieId;
    
    @DynamoDBAttribute
	private String cityId;
    
    @DynamoDBAttribute
	private String showTimeId;
    
    @DynamoDBAttribute
	private List<String> seatIds;
	
	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @DynamoDBAttribute
	private Date bookingDate;
	
	//adding for test 
	
	
	
	

}
