package com.cg.bms.cityservice.model;

import java.util.List;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@DynamoDBTable(tableName = "City")
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Getter
@Setter
public class City {
	
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	//@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
	private String _id;
	
    @DynamoDBAttribute
	private String name;
    
    @DynamoDBAttribute
	private String state;
    
    @DynamoDBAttribute
	private List<String> theatreIds;

}
