version: 0.2


phases:
  pre_build:
    commands:
      - mvn clean install
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 332958113406.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t booking-service:latest .
      - docker tag booking-service:latest 332958113406.dkr.ecr.us-east-1.amazonaws.com/booking-service:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 332958113406.dkr.ecr.us-east-1.amazonaws.com/booking-service:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"booking-service-container","imageUri":"%s"}]' 332958113406.dkr.ecr.us-east-1.amazonaws.com/booking-service:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
  files:
   - imagedefinitions.json
   - target/booking-service-container.jar